version: "2.1"
services:
  api:
    build: ./api/
    container_name: jamia_api
    restart: always
    mem_limit: 1GB
    networks:
      - docker_net
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - NODE_ENV
      - VIRTUAL_HOST=${JAMIA_API_HOSTNAME}
      - VIRTUAL_NETWORK=docker_net
      - LETSENCRYPT_HOST=${JAMIA_API_HOSTNAME}
      - LETSENCRYPT_EMAIL=${OFFICE_EMAIL}

  website:
    build: ./www/
    container_name: jamia_website
    restart: always
    mem_limit: 1GB
    networks:
      - docker_net
    environment:
      - VIRTUAL_HOST=${JAMIA_WEBSITE_HOSTNAME}
      - VIRTUAL_NETWORK=docker_net
      - LETSENCRYPT_HOST=${JAMIA_WEBSITE_HOSTNAME}
      - LETSENCRYPT_EMAIL=${OFFICE_EMAIL}

networks:
  docker_net:
    driver: bridge
