version: "2.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - docker_net
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./server/proxy/htpasswd:/etc/nginx/htpasswd
      - ./server/proxy/certs:/etc/nginx/certs:ro
      - ./server/proxy/timeout.conf:/etc/nginx/conf.d/timeout.conf

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    networks:
      - docker_net
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./server/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    networks:
      - docker_net
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./server/proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  api:
    build: ./api/
    container_name: jamia_api
    restart: always
    mem_limit: 1GB
    networks:
      - docker_net
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - API_PORT=5000
      - MONGODB_USER
      - MONGODB_PASS
      - VIRTUAL_HOST=${JAMIA_API_HOSTNAME}
      - VIRTUAL_NETWORK=docker_net
      - LETSENCRYPT_HOST=${JAMIA_API_HOSTNAME}
      - LETSENCRYPT_EMAIL=${OFFICE_EMAIL}

  website:
    build: ./www/
    container_name: jamia_website
    restart: always
    mem_limit: 1GB
    networks:
      - docker_net
    environment:
      - VIRTUAL_HOST=${JAMIA_WEBSITE_HOSTNAME}
      - VIRTUAL_NETWORK=docker_net
      - LETSENCRYPT_HOST=${JAMIA_WEBSITE_HOSTNAME}
      - LETSENCRYPT_EMAIL=${OFFICE_EMAIL}

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    mem_limit: 2GB
    networks:
      - docker_net
    environment:
      - MONGODB_USER
      - MONGODB_PASS

  redisstore:
    image: redis
    container_name: redisstore
    restart: always
    mem_limit: 2GB
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
    external: true